### ISSUE TITLE
Support batch actions

### ISSUE THREAD

**Issue by seoker** [nswbmw/ioredis-ratelimit#3]
In some cases, a single request might require batch actions, for example:
A user can draw 10 times per day, if a certain user want to draw 3 times in a row when he has 2 times left today. There are three options for this case:
(1) Do not count attempts exceeding the limit. Batch increments can be partially accepted by filling the existing space.
(2) Do not count attempts exceeding the limit. When batching, either the whole request is accepted or discarded.
(3) Accept the request and every attempt counts, including those above the limit.

**Comment by seoker** [comment]
If the features is implemented, An additional property should be returned to address how many actions are accepted, named like `acknowledged`.

**Comment by nswbmw** [comment]
Generally, we will set `ratelimit` a big threshold(like: 5000), normal user will not reach this. `ratelimit`'s main role is to prevent malicious brush your API.

**Comment by seoker** [comment]
In some of my scenarios, I would like to implement a limiter which allows user to send multi actions in a single request. The threshold will be large enough to 24h, and the limit will be like 50 times / 24h.

I was looking for a proper solution but couldn't find something workable for me. Actually, I'm willing to implement the feature with the capacities I addressed above to meet my requirement. I had tried https://github.com/RisingStack/rate-limiter but it seems not work and I have no idea how to fix it at this moment.

I'll send a PR later when I finish the test cases. If you're willing to accept, I'll suggest to bump a major version since the `key` will be invoked with the first argument only where the second is used to address number of actions. Also, I had removed `next` that is added by mistake.

**Comment by seoker** [comment]
Just send a PR, please kindly review it and accept if you'd like.

**Comment by nswbmw** [comment]
@seoker 
> and the limit will be like 50 times / 24h.

try [limiter](https://www.npmjs.com/package/limiter) ?

**Comment by seoker** [comment]
@nswbmw 

Thanks, but the module seems not based on `ioredis` and even not redis-based, cannot handle requests across servers.
Moreover, I want the key could be specified as different user should have their own limiter.

**Comment by seoker** [comment]
Hi @nswbmw 

Hope to hear any comment from you, no matter you would take it or not :)

**Comment by nswbmw** [comment]
I have not much time for this repo, added you to collaborator...

**Comment by seoker** [comment]
Sure I can contribute but would like to hear from you if you agree my modification and release a v2.0.0 hereby, or you wanna keep this library as simple as possible?

**Comment by nswbmw** [comment]
v2.0.0 LGTM
